// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ceazqjuuyskeohqftygi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlYXpxanV1eXNrZW9ocWZ0eWdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MTA1NDIsImV4cCI6MjA3Mzk4NjU0Mn0.mj4937vt2Hiwa7JYJM7DLLw_MIUpwx-e3UgIfWI3x1g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});